name: Lint assets - JS, CSS
description: "Lint assets - JS, CSS"

inputs:
  NODE_VERSION:
    type: string
    description: "Node.js version to use. Available options are 14, 16, latest etc. Default is latest."
    required: true
  PROJECT_PATH:
    type: string
    description: "Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>"
    required: true
  USE_CHECKOUT:
    type: string
    description: "If true, checkout is used to install dependencies"
    default: true

runs:
  using: composite
  steps:
    - name: Checkout
      if: inputs.USE_CHECKOUT == 'true'
      uses: actions/checkout@v6

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install assets packages with bun
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: |
        bun install --ignore-scripts --frozen-lockfile
        bun run build

    - name: Run linter - JS with bun
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: bun run lintJs

    - name: Run linters - CSS with bun
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: bun run lintStyle
