name: Send Slack notification

inputs:
  SLACK_WEBHOOK:
    description: 'Slack webhook URL'
    required: true
  SLACK_TITLE:
    type: string
    description: 'Title to use before main Slack message.'
    default: ''
  MSG_MINIMAL:
    type: string
    description: 'If set to true, removes: Ref, Event, Actions URL and Commit from the message. You can optionally whitelist any of these 4 removed values by passing it comma separated to the variable instead of true. (ex: MSG_MINIMAL: event or MSG_MINIMAL: ref,actions url, etc.)'
    default: 'ref,actions url'
  SLACK_ICON_EMOJI:
    type: string
    description: 'User/Bot icon shown with Slack message, in case you do not wish to add a URL for slack icon, you can set slack emoji in this env variable.'
    default: ':github:'
  SLACK_USERNAME:
    type: string
    description: 'Custom Slack Username sending the message. Does not need to be a "real" username.'
    default: 'GitHub Actions'
  SLACK_MESSAGE_ON_SUCCESS:
    type: string
    description: 'If set, will send the provided message instead of the default message when the passed status (through SLACK_COLOR) is success.'
    default: 'Deployment successful!'
  SLACK_MESSAGE_ON_FAILURE:
    type: string
    description: 'If set, will send the provided message instead of the default message when the passed status (through SLACK_COLOR) is failure.'
    default: 'Deployment failed!'
  SLACK_MESSAGE_ON_CANCEL:
    type: string
    description: 'If set, will send the provided message instead of the default message when the passed status (through SLACK_COLOR) is cancelled.'
    default: 'Deployment cancelled!'
  SLACKIFY_MARKDOWN:
    type: string
    description: 'If set to true, it will convert markdown to slack format.'
    default: 'false'

runs:
  using: composite
  steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.3.0
      env:
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
        MSG_MINIMAL: ${{ inputs.MSG_MINIMAL }}
        SLACK_TITLE: ${{ inputs.SLACK_TITLE }}
        SLACK_ICON_EMOJI: ${{ inputs.SLACK_ICON_EMOJI }}
        SLACK_USERNAME: ${{ inputs.SLACK_USERNAME }}
        SLACK_MESSAGE_ON_SUCCESS: ${{ inputs.SLACK_MESSAGE_ON_SUCCESS }}
        SLACK_MESSAGE_ON_FAILURE: ${{ inputs.SLACK_MESSAGE_ON_FAILURE }}
        SLACK_MESSAGE_ON_CANCEL: ${{ inputs.SLACK_MESSAGE_ON_CANCEL }}
        SLACK_COLOR: ${{ job.status }}
        SLACKIFY_MARKDOWN: ${{ inputs.SLACKIFY_MARKDOWN }}
