name: Lint assets - JS, CSS

inputs:
  NODE_VERSION:
    type: string
    description: 'Node.js version to use. Available options are 14, 16, latest etc. Default is latest.'
    required: true
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node.js version - ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: npm
        cache-dependency-path: (${{ inputs.PROJECT_PATH }} == '') ? 'package-lock.json' : "${{ inputs.PROJECT_PATH }}/package-lock.json"

    - name: Install assets packages
      working-directory: (${{ inputs.PROJECT_PATH }} == '') ? '.' : ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: |
        npm ci --no-progress --no-dev --no-audit
        npm run build

    - name: Run linter - JS
      working-directory: (${{ inputs.PROJECT_PATH }} == '') ? '.' : ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: npm run lintJs

    - name: Run linters - CSS
      working-directory: (${{ inputs.PROJECT_PATH }} == '') ? '.' : ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: npm run lintStyle
