name: Cleanup project theme/plugin

inputs:
  PROJECT_PATH:
    type: string
    description: "Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>"
    required: true

runs:
  using: composite
  steps:
    - name: Post install cleanup - project
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: |
        rm -rf tests/
        rm -rf node_modules/
        rm -rf assets/
        rm -rf src/Blocks/assets/
        rm -f composer.json
        rm -f package.json

        # Find and delete specified file types, excluding vendor, public folders and style.css
        find . -type f \( -name "*.js" -o -name "*.css" -o -name "*.scss" \
          -o -name "*.yml" -o -name "*.mjs" -o -name "*.md" -o -name "*.lock" \
          -o -name "*.lockb" -o -name "*.xml" -o -name "*.phar" -o -name "*.tmpl" -o -name "*.dist" \) \
          ! -path "./vendor*" \
          ! -path "*/vendor*" \
          ! -path "./public*" \
          ! -path "*/public*" \
          ! -name "style.css" \
          -delete

        # Delete hidden dot files, excluding vendor and public folders
        find . -type f -name ".*" \
          ! -path "./vendor*" \
          ! -path "*/vendor*" \
          ! -path "./public*" \
          ! -path "*/public*" \
          ! -name "." ! -name ".." \
          -delete

        # Find and delete empty directories (excluding vendor and public folders)
        find . -type d -empty \
          ! -path "./vendor*" \
          ! -path "*/vendor*" \
          ! -path "./public*" \
          ! -path "*/public*" \
          -delete
