name: Install WordPress with core and paid plugins

inputs:
  PHP_VERSION:
    type: string
    description: "PHP version to use. Available options are 7.4, 8.0, etc."
    required: true
  SETUP_FILE:
    type: string
    description: "Path to the setup file"
    default: "setup.json"
  WORDPRESS_GH_ACTIONS:
    type: string
    description: "GitHub PAT token for the WordPress repository deployment"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the project repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.WORDPRESS_GH_ACTIONS }}
        submodules: true

    - name: Setup variables
      id: variablesSetup
      shell: bash
      run: |
        echo "CORE_VERSION=$(cat ${{ inputs.SETUP_FILE }} | jq -r '.core')" >> "$GITHUB_OUTPUT"

    - name: Start MySQL
      shell: bash
      run: |
        sudo /etc/init.d/mysql start

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.PHP_VERSION }}
        coverage: none
        tools: composer:v2, wp-cli

    - name: Download WordPress core
      shell: bash
      run: |
        curl -Os https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

        php wp-cli.phar core download --version="${{ steps.variablesSetup.outputs.CORE_VERSION }}" --skip-content

    - name: WordPress setup wp-config.php
      shell: bash
      run: |
        php wp-cli.phar config create --dbname=wordpress_test --dbuser=root --dbpass=root --dbhost=127.0.0.1:3306 --skip-check
        php wp-cli.phar config delete WP_DEBUG

        wp config set "configProjectPath" "__DIR__ . \DIRECTORY_SEPARATOR . 'wp-config-project.php'" --raw --type="variable"
        wp config set "configProject" 'file_exists($configProjectPath) ? require_once($configProjectPath) : ""' --raw --type="variable"

        wp config set "constantsPath" "__DIR__ . \DIRECTORY_SEPARATOR . 'eightshift/constants.php'" --raw --type="variable"
        wp config set "constants" 'file_exists($constantsPath) ? require_once($constantsPath) : ""' --raw --type="variable"

    - name: WordPress setup database
      shell: bash
      run: |
        php wp-cli.phar db create

    - name: WordPress core install
      shell: bash
      run: |
        php wp-cli.phar core install --url=test.test --title="Deploy" --admin_user=test --admin_password=test --admin_email=test@test.com
