name: PHP check coding standards

inputs:
  PHP_VERSION:
    type: string
    description: 'PHP version to use. Available options are 8.2, 8.3, etc.'
    required: true
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.PHP_VERSION }}
        coverage: none

    - name: Install dependencies
      uses: "ramsey/composer-install@v3"
      with:
        working-directory: ${{ inputs.PROJECT_PATH }}

    - name: Run PHP check coding standards
      shell: bash
      working-directory: ${{ inputs.PROJECT_PATH }}
      run: "php ./vendor/squizlabs/php_codesniffer/bin/phpcs --runtime-set testVersion ${{ inputs.PHP_VERSION }}-"
