name: Continuous Integration - Plugin

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint assets JS and CSS using Node version - ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["latest"]
    steps:
      - name: Lint assets
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/assets@main
        with:
          NODE_VERSION: ${{ matrix.node }}
          PROJECT_PATH: "."
          USE_BUN: true

  phpstan:
    name: PHP static code analysis using PHP - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.4"]
    steps:
      - name: PHP Static code analysis
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/php-stan@main
        with:
          PHP_VERSION: ${{ matrix.php }}
          PROJECT_PATH: "."

  phpcs:
    name: PHP check coding standards using PHP - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.4"]
    steps:
      - name: PHP check coding standards
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/php-cs@main
        with:
          PHP_VERSION: ${{ matrix.php }}
          PROJECT_PATH: "."
