name: Bundle to release

inputs:
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true
  REPO_NAME:
    type: string
    description: 'Name of the repository without organization name. Example: eightshift-forms'
    required: true
  WORDPRESS_GH_ACTIONS:
    description: 'GitHub PAT token for the WordPress repository deployment'
    required: true
  OUTPUT_NAME:
    description: 'Name of the output zip file'
    default: 'release'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bundle theme/plugin
      uses: infinum/eightshift-deploy-actions-public/.github/actions/setup-theme-or-plugin@main
      with:
        ROOT_PATH: $GITHUB_WORKSPACE
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}

    - name: Zip Folder
      run: zip -r ${{ inputs.OUTPUT_NAME }}.zip ${{ inputs.REPO_NAME }}

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.WORDPRESS_GH_ACTIONS }}
        file: ${{ inputs.OUTPUT_NAME }}.zip
        tag: ${{ github.ref }}
        overwrite: true
