name: Cleanup project from root

inputs:
  PROJECT_PATH:
    type: string
    description: "Path to the project root."
    default: "."

runs:
  using: composite
  steps:
    - name: Post install cleanup - root
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: |
        rm -rf bin/
        rm -rf wp-content/uploads/
        rm -f wp-config-sample.php
        rm -f setup.json

        # Find and delete specified file types in current directory only (no recursion), excluding style.css
        find . -maxdepth 1 -type f \( -name "*.js" -o -name "*.css" -o -name "*.scss" \
          -o -name "*.yml" -o -name "*.mjs" -o -name "*.md" -o -name "*.lock" \
          -o -name "*.lockb" -o -name "*.xml" -o -name "*.tmpl" -o -name "*.dist" \) \
          -delete

        # Delete hidden dot files and directories in current directory
        find . -maxdepth 1 \( -type f -o -type d \) -name ".*" ! -name "." ! -name ".." -delete
