name: Cleanup project from root

runs:
  using: composite
  steps:
    - name: Post install cleanup - root
      shell: bash
      run: |
        rm -rf bin/
        rm -rf wp-content/uploads/
        rm -f wp-config-sample.php

        # Find and delete specified file types in current directory only (no recursion), excluding style.css
        find . -maxdepth 1 -type f \( -name "*.js" -o -name "*.css" -o -name "*.scss" -o -name "*.json" \
          -o -name "*.yml" -o -name "*.mjs" -o -name "*.md" -o -name "*.lock" \
          -o -name "*.lockb" -o -name "*.xml" -o -name "*.phar" -o -name "*.tmpl" -o -name "*.dist" -o -name ".*" \) \
          ! -path "./vendor*" \
          ! -name "style.css" \
          -delete
