name: Bundle to release

inputs:
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true
  REPO_NAME:
    type: string
    description: 'Name of the repository without organization name. Example: eightshift-forms'
    required: true
  WORDPRESS_GH_ACTIONS:
    description: 'GitHub PAT token for the WordPress repository deployment'
    required: true
  OUTPUT_NAME:
    description: 'Name of the output zip file'
    default: 'release'
  PHP_VERSION:
    type: string
    description: 'PHP version to use. Available options are 7.4, 8.0, etc.'
    required: true
  USE_NODE:
    type: string
    description: "Set do default if you don't have node_modules folder in your project."
    default: true
  NODE_VERSION:
    type: string
    description: 'Node.js version to use. Available options are 14, 16, latest etc. Default is latest.'
    default: 'latest'
  USE_BUN:
    type: string
    description: "If true, bun is used instead of npm for running scripts"
    default: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.PHP_VERSION }}
        coverage: none

    - name: Bundle theme/plugin
      uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/theme-or-plugin@docker
      with:
        ROOT_PATH: $GITHUB_WORKSPACE
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
        USE_NODE: ${{ inputs.USE_NODE }}
        USE_BUN: ${{ inputs.USE_BUN }}
        NODE_VERSION: ${{ inputs.NODE_VERSION }}

    - name: Post install cleanup - root
      uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/root@docker

    - name: Zip Folder
      shell: bash
      run: |
        mkdir ${{ inputs.REPO_NAME }}
        rsync -r --exclude '${{ inputs.REPO_NAME }}' * ${{ inputs.REPO_NAME }}
        zip -rq ${{ inputs.OUTPUT_NAME }}.zip ${{ inputs.REPO_NAME }}

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.WORDPRESS_GH_ACTIONS }}
        file: ${{ inputs.OUTPUT_NAME }}.zip
        tag: ${{ github.ref }}
        overwrite: true
