name: Install theme/plugin from submodule

inputs:
  NODE_VERSION:
    type: string
    description: 'Node.js version to use. Available options are 14, 16, latest etc. Default is latest.'
    default: 'latest'
  ROOT_PATH:
    type: string
    description: 'Path to the root of the repository. Usually $GITHUB_WORKSPACE'
    required: true
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true
  SUBMODULE_PATH:
    type: string
    description: 'Path to the root submodule folder from the root of the repository. Usually wordpress-infinum-web-redesign'
    required: true
  SUBMODULE_PROJECT_PATH:
    type: string
    description: 'Path to the submodule project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true
  USE_BUN:
    type: string
    description: "If true, bun is used instead of npm for running scripts"
    default: false

runs:
  using: composite
  steps:
    - name: Use the subdirectory theme
      shell: bash
      run: |
        rm -rf ${{ inputs.ROOT_PATH }}/${{ inputs.PROJECT_PATH }}
        cp -r ${{ inputs.ROOT_PATH }}/${{ inputs.SUBMODULE_PATH }}/${{ inputs.SUBMODULE_PROJECT_PATH }}/. ${{ inputs.ROOT_PATH }}/${{ inputs.PROJECT_PATH }}
        rm -rf ${{ inputs.ROOT_PATH }}/${{ inputs.SUBMODULE_PATH }}

    - name: Install Node.js
      if: inputs.USE_BUN == 'false'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: npm
        cache-dependency-path: "${{ inputs.PROJECT_PATH }}/package-lock.json"

    - name: Install Node.js
      if: inputs.USE_BUN == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache-dependency-path: "${{ inputs.PROJECT_PATH }}/bun.lock"

    - name: Install Bun
      if: inputs.USE_BUN == 'true'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      uses: "ramsey/composer-install@v3"
      with:
        composer-options: "--no-dev"
        working-directory: ${{ inputs.PROJECT_PATH }}

    - name: Install assets packages with npm
      if: inputs.USE_BUN == 'false'
      working-directory: ${{ inputs.PROJECT_PATH }}
      shell: bash
      run: |
        npm ci --no-progress --no-dev --no-audit
        npm run build

    - name: Install assets packages with bun
      working-directory: ${{ inputs.PROJECT_PATH }}
      if: inputs.USE_BUN == 'true'
      shell: bash
      run: |
        bun install --frozen-lockfile --production
        bun run build

    - name: Post install cleanup - theme from submodule
      uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/project@main
      with:
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
