name: Rollback

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: "Target Environment"
        required: true
        default: "staging"
        options:
          - staging
          - production
      ROLLBACK_NUMBER:
        description: "Number of release to rollback to. Current release if number 1, to rollback to the previous release enter number 2 or more."
        required: true
        default: "2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    name: Setup context - ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || 'staging' }}
    outputs:
      environment: ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || 'staging' }}
    steps:
      - id: get
        run: |
          echo "environment=${{ inputs.ENVIRONMENT }}" >> "$GITHUB_OUTPUT"

  rollback:
    name: Rollback
    needs: [context]
    steps:
      - name: Rollback release
        uses: infinum/eightshift-deploy-actions-public/.github/actions/ssh/rollback@main
        with:
          ROLLBACK_NUMBER: ${{ github.event.inputs.ROLLBACK_NUMBER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_ROOT: ${{ secrets.SERVER_ROOT }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SSM_DEPLOY: true
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    environment: ${{ needs.context.outputs.environment }}
    needs: [context, rollback]
    steps:
      - name: Notify
        uses: infinum/eightshift-deploy-actions-public/.github/actions/slack-notification@main
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
