name: Run composer actions
description: "Run composer actions - PHPStan, CodeSniffer, etc."

inputs:
  PHP_VERSION:
    type: string
    description: "PHP version to use. Available options are 8.2, 8.3, 8.4, etc."
    required: false
    default: "8.4"
  PROJECT_PATH:
    type: string
    description: "Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>"
    required: true
  WORDPRESS_GH_ACTIONS:
    type: string
    description: "GitHub PAT token for the WordPress repository deployment"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.PHP_VERSION }}
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      uses: "infinum/eightshift-deploy-actions-public/.github/actions/set/composer-install@main"
      with:
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
        WORDPRESS_GH_ACTIONS: ${{ inputs.WORDPRESS_GH_ACTIONS }}

    - name: Run Composer checks
      shell: bash
      working-directory: ${{ inputs.PROJECT_PATH }}
      run: "composer run test"
