name: Continuous Integration - Theme

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint assets JS and CSS using Node version - ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 'latest' ]
    steps:
      - name: Lint assets
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/assets@docker
        with:
          NODE_VERSION: ${{ matrix.node }}
          PROJECT_PATH: wp-content/themes/<theme-name>

  phpstan:
    name: PHP static code analysis using PHP - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
    steps:
      - name: PHP Static code analysis
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/php-stan@docker
        with:
          PHP_VERSION: ${{ matrix.php }}
          PROJECT_PATH: wp-content/themes/<theme-name>

  phpcs:
    name: PHP check coding standards using PHP - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
    steps:
      - name: PHP check coding standards
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/php-@docker
        with:
          PHP_VERSION: ${{ matrix.php }}
          PROJECT_PATH: wp-content/themes/<theme-name>

