name: Bundle to artifact

inputs:
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name> or wp-content/plugins/<plugin_name>'
    required: true
  REPO_NAME:
    type: string
    description: 'Name of the repository without organization name. Example: eightshift-forms'
    required: true
  WORDPRESS_GH_ACTIONS:
    description: 'GitHub PAT token for the WordPress repository deployment'
    required: true
  OUTPUT_NAME:
    description: 'Name of the output zip file'
    default: 'release'
  PHP_VERSION:
    type: string
    description: 'PHP version to use. Available options are 7.4, 8.0, etc.'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.PHP_VERSION }}
        coverage: none

    - name: Bundle theme/plugin
      uses: infinum/eightshift-deploy-actions-public/.github/actions/setup-theme-or-plugin@main
      with:
        ROOT_PATH: $GITHUB_WORKSPACE
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}

    - name: Post install cleanup - root
      uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup-project-root@main

    - name: Zip Folder
      shell: bash
      run: zip -rq ${{ inputs.OUTPUT_NAME }}.zip .

    - uses : actions/upload-artifact@v2
      with:
        name: ${{ inputs.OUTPUT_NAME }}
        path: ${{ inputs.OUTPUT_NAME }}.zip
