name: Bundle release - Plugin

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Add zip to release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["latest"]
        php: ["8.3"]
    steps:
      - name: Setup WordPress
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/wordpress@main
        with:
          PHP_VERSION: "8.3"
          WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}

      - name: Setup custom secrets as environment variables
        shell: bash
        run: |
          wp config set WP_ENVIRONMENT_TYPE 'production'

      - name: Install plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/theme-or-plugin@main
        with:
          PROJECT_PATH: "wp-content/plugins/<plugin_name>"
          USE_BUN: true

      - name: Set cache
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/cache@main
        with:
          PROJECT_PATH: "wp-content/plugins/<plugin_name>"

      - name: Post install cleanup - plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/project@main
        with:
          PROJECT_PATH: "wp-content/plugins/<plugin_name>"

      - name: Setup correct folder/file permissions
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/permissions@main

      - name: Zip Plugin
        shell: bash
        run: |
          zip -rq <plugin_name>.zip wp-content/plugins/<plugin_name>

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ inputs.WORDPRESS_GH_ACTIONS }}
          file: <plugin_name>.zip
          tag: ${{ github.ref }}
          overwrite: true
