name: Update theme version number

inputs:
  ROOT_PATH:
    type: string
    description: 'Path to the root of the repository. Usually $GITHUB_WORKSPACE'
    required: true
  PROJECT_PATH:
    type: string
    description: 'Path to the project folder from the root of the repository. Usually wp-content/themes/<theme_name>'
    required: true

runs:
  using: composite
  steps:
    - name: Update theme version number
      shell: bash
      with:
        working-directory: ${{ inputs.PROJECT_PATH }}
      run: |
        VERSION=${{ github.sha }}

        sed -i -E "s/Version:[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+/Version: $VERSION/" "style.css"
        sed -i -E "s/Version:[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+/Version: $VERSION/" "functions.php"

        echo "Version number updated successfully to $VERSION."

